
package com.avathartech.sparkjavasoap.cliente.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AcademicoWebServiceService", targetNamespace = "http://soap.sparkjavasoap.avathartech.com/", wsdlLocation = "http://localhost:7777/ws/AcademicoWebService?wsdl")
public class AcademicoWebServiceService
    extends Service
{

    private final static URL ACADEMICOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACADEMICOWEBSERVICESERVICE_EXCEPTION;
    private final static QName ACADEMICOWEBSERVICESERVICE_QNAME = new QName("http://soap.sparkjavasoap.avathartech.com/", "AcademicoWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/AcademicoWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACADEMICOWEBSERVICESERVICE_WSDL_LOCATION = url;
        ACADEMICOWEBSERVICESERVICE_EXCEPTION = e;
    }

    public AcademicoWebServiceService() {
        super(__getWsdlLocation(), ACADEMICOWEBSERVICESERVICE_QNAME);
    }

    public AcademicoWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACADEMICOWEBSERVICESERVICE_QNAME, features);
    }

    public AcademicoWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ACADEMICOWEBSERVICESERVICE_QNAME);
    }

    public AcademicoWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACADEMICOWEBSERVICESERVICE_QNAME, features);
    }

    public AcademicoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcademicoWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcademicoWebService
     */
    @WebEndpoint(name = "AcademicoWebServicePort")
    public AcademicoWebService getAcademicoWebServicePort() {
        return super.getPort(new QName("http://soap.sparkjavasoap.avathartech.com/", "AcademicoWebServicePort"), AcademicoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcademicoWebService
     */
    @WebEndpoint(name = "AcademicoWebServicePort")
    public AcademicoWebService getAcademicoWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.sparkjavasoap.avathartech.com/", "AcademicoWebServicePort"), AcademicoWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACADEMICOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ACADEMICOWEBSERVICESERVICE_EXCEPTION;
        }
        return ACADEMICOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
